blank_issues_enabled: true
contact_links:
  - name: ğŸ‘¨â€âš–ï¸ `jsmv` slack
    url: https://mavryk-dev.slack.com/archives/C061SSDBN69
    about: If you have a question about `jsmv`, please ask on our slack channel
